#!/bin/bash
#make SRC/ and run python file run.py for Nugrodis.

CURRENT_DIR=$PWD 

NuGroDis_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#oldVersion:  
#cd $NuGroDis_DIR/libMetallurgical/SRC/ && make &&cd ../.. && python run.py && cd $CURRENT_DIR

#NewVersion
cd $NuGroDis_DIR/libMetallurgical/SRC/ && make &&cd ../.. && python run.py; python -c "import script; print script.PostProcessing()" && cd $CURRENT_DIR