#!/bin/bash
#make SRC/ and run python file run.py for Nugrodis.

CURRENT_DIR=$PWD 

NuGroDis_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd $NuGroDis_DIR/libMetallurgical/SRC/ && make &&cd ../.. && python run.py && cd $CURRENT_DIR