
                 NAME = Metallurgical

	SRC_FILE_LIST = Computation.cpp \
			Hardening.cpp \
			PythonBindings.cpp \
			Quenching.cpp \
			ThermalLoading.cpp \
			ThermoDynamicsConstant.cpp


.SUFFIXES:

include ../../MAKE/Makefile.LIB_SRC.inc
