
                 NAME = Metallurgical

	SRC_FILE_LIST = Computation.cpp \
			ChemicalElement.cpp \
			Hardening.cpp \
			PythonBindings.cpp \
			Quenching.cpp \
			ThermalLoading.cpp \
			ThermoDynamicsConstant.cpp \
			Vacancy.cpp \
			RadiusDistribution.cpp \
			


.SUFFIXES:

include ../../MAKE/Makefile.LIB_SRC.inc
