
                 NAME = Metallurgical

	SRC_FILE_LIST = ChemicalComposition.cpp\
			Boundary.cpp\
			ChemicalElement.cpp\
			Concentration.cpp \
			Computation.cpp \
			Diffusion.cpp\
			Grain.cpp\
			GuinierPreston.cpp \
			Hardening.cpp \
			InterfacialConcentration.cpp\
			Material.cpp \
			Polynomial.cpp\
			Precipitate.cpp\
			Quenching.cpp \
			RadiusDistribution.cpp \
			Sprime.cpp \
			SSGrain.cpp\
			Temperature.cpp \
			ThermalLoading.cpp \
			ThermoDynamicsConstant.cpp \
			Vacancy.cpp\
			PythonBindings.cpp\
			Util.cpp
			

#			PythonBindings.cpp \ Diffusion.cpp\ InterfacialConcentration.cpp\
			


.SUFFIXES:

include ../../MAKE/Makefile.LIB_SRC.inc
